name: GitHub Actions Demo

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ ".github/**" ]
    
  schedule:
    - cron: "15 6 * * sun"
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      # Runs a single command using the runners shell
      - name: Output Name of Triggering Event
        run: echo "The event was:" ${{ github.event_name }} 

      # Runs a set of commands using the runners shell
      - name: Output Branch Name
        run: echo "The branch name is:" ${GITHUB_REF##*/}
        
      - name: List All Repo Files
        run:  |
          echo "The files listed as follows:"
          ls
